/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homebudget.frames;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Aladser
 */
public class infoDialog extends javax.swing.JDialog {

    TrsctFrame owner;
    /**
     * Creates new form infoDialog
     * @param parent
     * @param modal
     */
    public infoDialog(TrsctFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        owner = (TrsctFrame) parent;
        textArea.setText("\n\n         Домашний бюджет"
                             + "\n            версия 1221\n"
                             + "\n          (с)Aladser 2021г.");
        
        int x =  parent.getX() + (parent.getWidth() - getWidth())/2;
        int y =  parent.getY() + (parent.getHeight() - getHeight())/2;
        setLocation(x, y);
        getContentPane().setBackground(Color.white);
        textArea.setFont(parent.DIGFONT.deriveFont(Font.PLAIN, 18));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Информация");

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setRows(3);
        jScrollPane1.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
